export const ADD_ITEM = 'ADD_ITEM';
export const ADD_SUB_ITEM = 'ADD_SUB_ITEM';
export const EMPTY_SUB_ITEMS = 'EMPTY_SUB_ITEMS';
export const TOGGLE_VISIBLE_ITEM = 'TOGGLE_VISIBLE_ITEM';
export const TOGGLE_EXPAND_ITEM = 'TOGGLE_EXPAND_ITEM';
export const TOGGLE_EXPAND_ALL_ITEMS = 'TOGGLE_EXPAND_ALL_ITEMS';
export const SET_CURRENT_PARENT_LEVEL = 'SET_CURRENT_PARENT_LEVEL';
